pipeline {
    agent { label 'slave_node' }
    stages {
        stage ("checkout") {
            steps {
                git branch: 'main',url : 'https://github.com/Narasimha88-bot/k8_Opsnova_bookStore.git'
            }
        }
        stage ('build the image') {
            steps {
                dir ('catalog-service') {
                    sh 'docker build -t catalog-service:latest .'
                }
            }
        }
        stage ('tag the image')
        {
            steps {
                dir ('catalog-service') {
                    sh 'docker tag catalog-service:latest  183004894778.dkr.ecr.us-east-1.amazonaws.com/nellore/sampe-repo:latest'
                }
            }
        }
        stage ('push the image') {
            steps {
                dir ('catalog-service') {
                    sh 'docker push  183004894778.dkr.ecr.us-east-1.amazonaws.com/nellore/sampe-repo:latest'
                }
            }
        }
    }
}
